# Generated by Django 3.0.7 on 2020-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='mission_accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
