# Generated by Django 3.0.7 on 2020-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_milestone_mission_accomplished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='milestones',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='good_first_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='medium_question_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='medium_question_2',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
