# Generated by Django 3.0.7 on 2020-06-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_milestone_mission_accomplished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='almost_there',
            new_name='good_first_issue',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='good_start',
            new_name='medium_question_1',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='mission_accomplished',
            new_name='medium_question_2',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='terrific_start',
        ),
    ]
