# Generated by Django 3.0.7 on 2020-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200622_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='medium_question_1',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='medium_question_2',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='hard_issues_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='medium_issues_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='pr_merged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='pr_opened',
            field=models.IntegerField(default=0),
        ),
    ]
