# Generated by Django 3.0.7 on 2020-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200622_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
