# Generated by Django 3.0.7 on 2020-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200622_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='milestone_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
