# Generated by Django 3.0.7 on 2020-06-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_leaderboard_milestone_achieved'),
        ('profiles', '0005_auto_20200623_1509'),
    ]

    operations = [
    ]
