# Generated by Django 3.0.7 on 2020-06-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_20200623_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='username',
            new_name='user',
        ),
    ]
